//! `deathblow_script <out.txt>`: plans an input script for `--play --lock-on --simple-ai` in
//! which Wolf deflects the soldier's slashes until its posture breaks and then deathblows it.
//! Prints the steps worth a screenshot. Run from the repository root.
//!
//! The duel is deterministic, so the planner replays it from the start for each slash, finds
//! the step the blade lands, and presses guard two steps before it (inside the 12-step
//! just-guard window of 105010).

use sekiro_sim::duel::Duel;
use sekiro_sim::{Buttons, InputFrame};
use std::path::Path;

const DT: f32 = 1.0 / 60.0;

fn input(presses: &[usize], attack_at: Option<usize>, i: usize) -> InputFrame {
    InputFrame {
        buttons: Buttons {
            guard: presses.iter().any(|&p| i >= p && i < p + 3),
            attack: attack_at.is_some_and(|a| i >= a && i < a + 3),
            lock_on: i == 0,
            ..Buttons::default()
        },
        ..InputFrame::default()
    }
}

fn duel() -> Duel {
    let mut d = Duel::load(Path::new("cache"), 6.0).expect("cache");
    d.use_simple_ai();
    d
}

fn main() {
    let out = std::env::args()
        .nth(1)
        .expect("usage: deathblow_script <out.txt>");
    let mut presses: Vec<usize> = Vec::new();
    let mut broke_at = None;
    'slashes: for k in 0..8 {
        // Find the k-th soldier hit with the presses so far.
        let mut d = duel();
        let mut seen = 0;
        let mut hit_at = None;
        for i in 0..4000 {
            let r = d.step(&input(&presses, None, i), DT);
            if r.hits.iter().any(|(h, _)| h.attacker == 1) {
                if seen == k {
                    hit_at = Some(i);
                    break;
                }
                seen += 1;
            }
        }
        let hit_at = hit_at.expect("the soldier stopped attacking");
        for lead in [2, 1, 3, 4] {
            let mut trial = presses.clone();
            trial.push(hit_at - lead);
            let mut d = duel();
            let mut seen = 0;
            for i in 0..hit_at + 10 {
                let r = d.step(&input(&trial, None, i), DT);
                if let Some((_, res)) = r.hits.iter().find(|(h, _)| h.attacker == 1) {
                    seen += 1;
                    if seen <= k {
                        continue;
                    }
                    if res.deflected {
                        presses = trial;
                        eprintln!(
                            "deflect {k} at step {i}: soldier posture {} (-{})",
                            d.rules.fighters[1].posture.remaining, res.attacker_posture_damage
                        );
                        if res.posture_broke {
                            broke_at = Some(i);
                            break 'slashes;
                        }
                        continue 'slashes;
                    }
                    break;
                }
            }
        }
        panic!("no timing deflected slash {k}");
    }
    let broke_at = broke_at.expect("posture never broke");
    let attack_at = broke_at + 10;
    let end = attack_at + 420;
    let mut d = duel();
    let mut frames = Vec::new();
    for i in 0..end {
        let f = input(&presses, Some(attack_at), i);
        let r = d.step(&f, DT);
        if r.deathblow.started.is_some() {
            eprintln!(
                "deathblow starts at step {i}: rows {:?}",
                r.deathblow.started
            );
        }
        if r.deathblow.hit {
            eprintln!("deathblow lands at step {i}, killed {}", r.deathblow.killed);
        }
        frames.push(f);
    }
    // Run-length encode into the demo script format.
    let mut text = String::from("# generated by examples/deathblow_script.rs\n");
    let mut i = 0;
    while i < frames.len() {
        let mut n = 1;
        while i + n < frames.len() && frames[i + n].buttons == frames[i].buttons {
            n += 1;
        }
        let b = frames[i].buttons;
        let mut names = Vec::new();
        if b.guard {
            names.push("guard");
        }
        if b.attack {
            names.push("attack");
        }
        if b.lock_on {
            names.push("lock_on");
        }
        let names = if names.is_empty() {
            "-".to_string()
        } else {
            names.join(",")
        };
        text += &format!("{n} 0 0 {names}\n");
        i += n;
    }
    std::fs::write(&out, text).expect("write script");
    eprintln!("posture broke at step {broke_at}; attack at {attack_at}; {end} steps");
}
